# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "dev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
spec:
  description: "the git repository for the Dev environment"
  provider: "https://github.com"
  providerName: 'github'
  org: "ndtech-pipeline"
  repo: "jx3-kubernetes"
  httpCloneURL: "https://github.com/ndtech-pipeline/jx3-kubernetes.git"
  url: "https://github.com/ndtech-pipeline/jx3-kubernetes.git"
  scheduler:
    kind: Scheduler
    name: "environment"
